import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { cn } from "@/lib/utils";

import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "My Earth Kitchen",
    description: "Generated by create next app", // TODO: Update this
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <Toaster position="bottom-right" />
            <body className={cn(inter.className)}>{children}</body>
        </html>
    );
}
